// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NbicDragonflies.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NbicDragonflies.Resources.LanguageResource", typeof(LanguageResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GalleryLabel {
            get {
                return ResourceManager.GetString("GalleryLabel", resourceCulture);
            }
        }
        
        public static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        public static string IdentifyLabel {
            get {
                return ResourceManager.GetString("IdentifyLabel", resourceCulture);
            }
        }
        
        public static string NavigationLabel {
            get {
                return ResourceManager.GetString("NavigationLabel", resourceCulture);
            }
        }
        
        public static string ObservationListLabel {
            get {
                return ResourceManager.GetString("ObservationListLabel", resourceCulture);
            }
        }
        
        public static string ObservationMapLabel {
            get {
                return ResourceManager.GetString("ObservationMapLabel", resourceCulture);
            }
        }
        
        public static string ObservationsLabel {
            get {
                return ResourceManager.GetString("ObservationsLabel", resourceCulture);
            }
        }
        
        public static string RecentObsLabel {
            get {
                return ResourceManager.GetString("RecentObsLabel", resourceCulture);
            }
        }
        
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        public static string SpeciesLabel {
            get {
                return ResourceManager.GetString("SpeciesLabel", resourceCulture);
            }
        }
        
        public static string GalleryImageSpeciesLabel {
            get {
                return ResourceManager.GetString("GalleryImageSpeciesLabel", resourceCulture);
            }
        }
        
        public static string GalleryImagePhotographerLabel {
            get {
                return ResourceManager.GetString("GalleryImagePhotographerLabel", resourceCulture);
            }
        }
        
        public static string GalleryImageDateLabel {
            get {
                return ResourceManager.GetString("GalleryImageDateLabel", resourceCulture);
            }
        }
        
        public static string GalleryImageLicenseLabel {
            get {
                return ResourceManager.GetString("GalleryImageLicenseLabel", resourceCulture);
            }
        }
        
        public static string GalleryImageDescriptionLabel {
            get {
                return ResourceManager.GetString("GalleryImageDescriptionLabel", resourceCulture);
            }
        }
    }
}
