//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbicDragonflies.Resources
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NbicDragonflies.Resources.LanguageResource", typeof(LanguageResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Varsel.
        /// </summary>
        public static string AlertTitle
        {
            get
            {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dato.
        /// </summary>
        public static string GalleryImageDateLabel
        {
            get
            {
                return ResourceManager.GetString("GalleryImageDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string GalleryImageDescriptionLabel
        {
            get
            {
                return ResourceManager.GetString("GalleryImageDescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lisens.
        /// </summary>
        public static string GalleryImageLicenseLabel
        {
            get
            {
                return ResourceManager.GetString("GalleryImageLicenseLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trykk på bildet for mer informasjon.
        /// </summary>
        public static string GalleryImageMoreInfoLabel
        {
            get
            {
                return ResourceManager.GetString("GalleryImageMoreInfoLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fotograf.
        /// </summary>
        public static string GalleryImagePhotographerLabel
        {
            get
            {
                return ResourceManager.GetString("GalleryImagePhotographerLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string GalleryImageSpeciesLabel
        {
            get
            {
                return ResourceManager.GetString("GalleryImageSpeciesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Galleri.
        /// </summary>
        public static string GalleryLabel
        {
            get
            {
                return ResourceManager.GetString("GalleryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For best opplevelse vennligst slå på posisjon..
        /// </summary>
        public static string GeoLocatorOff
        {
            get
            {
                return ResourceManager.GetString("GeoLocatorOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hjem.
        /// </summary>
        public static string HomeLabel
        {
            get
            {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identifiser art.
        /// </summary>
        public static string IdentifyLabel
        {
            get
            {
                return ResourceManager.GetString("IdentifyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For best opplevelse vennligst slå på WiFi eller mobildata..
        /// </summary>
        public static string InternetOff
        {
            get
            {
                return ResourceManager.GetString("InternetOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For best opplevelse vennligst slå på WiFi eller mobildata..
        /// </summary>
        public static string InternetOff {
            get {
                return ResourceManager.GetString("InternetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spørsmål.
        /// </summary>
        public static string KeyQuestionsLabel
        {
            get
            {
                return ResourceManager.GetString("KeyQuestionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forslag.
        /// </summary>
        public static string KeyResultsLabel
        {
            get
            {
                return ResourceManager.GetString("KeyResultsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meny.
        /// </summary>
        public static string NavigationLabel
        {
            get
            {
                return ResourceManager.GetString("NavigationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        public static string ObservationListLabel
        {
            get
            {
                return ResourceManager.GetString("ObservationListLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kart.
        /// </summary>
        public static string ObservationMapLabel
        {
            get
            {
                return ResourceManager.GetString("ObservationMapLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Observasjoner.
        /// </summary>
        public static string ObservationsLabel
        {
            get
            {
                return ResourceManager.GetString("ObservationsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nylige observasjoner i.
        /// </summary>
        public static string RecentObsLabel
        {
            get
            {
                return ResourceManager.GetString("RecentObsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Søk arter ....
        /// </summary>
        public static string SearchLabel
        {
            get
            {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finner ingen resultater for.
        /// </summary>
        public static string SearchResultCouldNotFind
        {
            get
            {
                return ResourceManager.GetString("SearchResultCouldNotFind", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forslag.
        /// </summary>
        public static string SearchResultSuggestions
        {
            get
            {
                return ResourceManager.GetString("SearchResultSuggestions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string SearchTitle
        {
            get
            {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Egenskaper.
        /// </summary>
        public static string SpeciesInfoAttributes
        {
            get
            {
                return ResourceManager.GetString("SpeciesInfoAttributes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bilder.
        /// </summary>
        public static string SpeciesInfoImages
        {
            get
            {
                return ResourceManager.GetString("SpeciesInfoImages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arter.
        /// </summary>
        public static string SpeciesLabel
        {
            get
            {
                return ResourceManager.GetString("SpeciesLabel", resourceCulture);
            }
        }
    }
}